services:
  mysql:
    image: mysql:8.0
    ports:
      - '${FORWARD_DB_MYSQL_PORT:-3306}:3306'
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      #TZ: 'Asia/Hong_Kong'

  mongo:
    image: mongo:latest
    ports:
      - '${FORWARD_DB_MONGO_PORT:-27017}:27017'
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:latest
    ports:
      - '${FORWARD_DB_REDIS_PORT:-6379}:6379'
    volumes:
      - ./data/redis:/data
  postgres:
    image: postgres
    ports:
      - '${FORWARD_DB_POSTGRES_PORT:-5432}:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
    #healthcheck:
    #  test: [“CMD-SHELL”, “pg_isready”]
    #  interval: 1s
    #  timeout: 5s
    #  retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - '${FORWARD_ADMINER_PORT:-8080}:8080'
