services:
  db:
    image: mariadb
    # restart: always
    ports:
      - '${FORWARD_DB_MARIADB_PORT:-3308}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      # - ./config/mariadb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mariadb:/var/lib/mysql
    networks:
          - db-bridge

  mysql:
    image: mysql:8.0
    ports:
      - '${FORWARD_DB_MYSQL_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      #TZ: 'Asia/Hong_Kong'
    networks:
          - db-bridge

  mongo:
    image: mongo:latest
    ports:
      - '${FORWARD_DB_MONGO_PORT:-27017}:27017'
    volumes:
      - ./data/mongo:/data/db
    networks:
          - db-bridge

  redis:
    image: redis:latest
    ports:
      - '${FORWARD_DB_REDIS_PORT:-6379}:6379'
    volumes:
      - ./data/redis:/data
    networks:
          - db-bridge

  postgres:
    image: postgres
    ports:
      - '${FORWARD_DB_POSTGRES_PORT:-5432}:5432'
    # restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      # POSTGRES_USER: postgres
      # PGUSER: root
      # PGPASSWORD: root
      # PGDATABASE: root
    #healthcheck:
    #  test: [“CMD-SHELL”, “pg_isready”]
    #  interval: 1s
    #  timeout: 5s
    #  retries: 10
    networks:
          - db-bridge

  adminer:
    image: adminer
    # restart: always
    ports:
      - '${FORWARD_ADMINER_PORT:-8080}:8080'
    networks:
          - db-bridge
    depends_on: 
      - mysql
      - postgres
      - mongo
    links:
      - mysql
      - postgres
      - mongo

networks:
    db-bridge:
        driver: bridge